# Generated by Django 4.1 on 2022-08-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('current_page', models.IntegerField(blank=True, null=True)),
                ('total_page', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
